### ISSUE TITLE
Security Issue using emails

### ISSUE THREAD

**Issue by Saderyal** [quanhua92/next-auth-ioredis-adapter-example#1]
Hi, I recently discovered this adapter for Redis, which I found really great and easy to implement.
So, first of all, I want to thank you for your job :)

But, I found a really important vulnerability issue in verification-token based authentications (Email authentications).
Basically, I've seen that your `useVerificationToken` function simply checks if there is a verification token with the specified email, but it doesn't check if the token is valid or not.

This means that, for example, the user `example@test.com` can request an email to sign in, and a verification link will be sent in his mailbox. Everything, for now, it's Ok.
But then a potential hacker who knows that `example@test.com` is trying to authenticate, can simply access to his profile with a random token, because in the adapter there is not a token validation. So, the hacker can go to this URL:

```
http://localhost:3000/api/auth/callback/email?callbackUrl=http://localhost:3000&token=INVALID_RANDOM_TOKEN&email=example@test.com
```
And he will be successfully authenticated!

I resolved this issue by modifying the `useVerificationToken` function like this:

```javascript
async useVerificationToken(verificationToken) {
    const id = verificationToken.identifier;
    const token = await getVerificationToken(id);
    if (!token || verificationToken.token !== token.token)
      return null;
    await deleteVerificationToken(id);
    return token;
 },
```

Hope this helps! 👍🏻

Great Job with the adapter anyway! 🥳

**Comment by quanhua92** [comment]
Thank you very much. I haven't fully tested but I wonder if you can make a Pull Request so your suggestion can be recorded in the commit history.
😁

**Comment by Saderyal** [comment]
> 

Ok, Done :D

**Comment by quanhua92** [comment]
Thanks. I merged https://github.com/quanhua92/next-auth-ioredis-adapter-example/pull/2
